; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
lib_deps = 
	arduino-libraries/Servo@^1.2.2
	nicohood/PinChangeInterrupt@^1.2.9
	adafruit/Adafruit AHRS@^2.3.6
	adafruit/Adafruit L3GD20 U@^2.0.3
	pololu/L3G@^3.0.0
	adafruit/Adafruit LSM303 Accel@^1.1.8
	adafruit/Adafruit LSM303DLH Mag@^1.0.10
	adafruit/Adafruit Unified Sensor@^1.1.15
